# Generated by Django 5.0.3 on 2025-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Canceled', 'Canceled'), ('No-Show', 'No-Show')], default='Pending', max_length=20),
        ),
    ]
