# Generated by Django 5.0.3 on 2025-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='needs_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
