# Generated by Django 5.0.3 on 2025-06-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_needs_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'housekeeping'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
