# Generated by Django 5.0.3 on 2025-06-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_amenity_room_has_spa_room_spa_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
