# Generated by Django 5.0.3 on 2025-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_roomimage_caption_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='core.amenity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='spa_services',
            field=models.ManyToManyField(blank=True, to='core.spaservice'),
        ),
    ]
