# Generated by Django 5.0.3 on 2025-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_booking_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='has_spa',
        ),
        migrations.RemoveField(
            model_name='room',
            name='spa_description',
        ),
        migrations.AddField(
            model_name='room',
            name='spa_services',
            field=models.ManyToManyField(blank=True, to='core.spaservice'),
        ),
    ]
