# Generated by Django 5.0.3 on 2025-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_room_has_spa_remove_room_spa_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
