# Generated by Django 5.0.3 on 2025-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='booking_id_proofs/'),
        ),
    ]
