# Generated by Django 5.0.3 on 2025-07-03 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staffsalary_staffattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffsalary',
            old_name='salary_per_day',
            new_name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_salaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
