# Generated by Django 5.0.3 on 2025-07-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='needs_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
